### ISSUE TITLE
Multipart form with File

### ISSUE THREAD

**Issue by m0n9oose** [jhiesey/stream-http#113]
Is it possible to send multipart form with a File (Blob)? I have tried to use same approach as with nodejs http module but no luck, request has empty body.

P.S. i'm trying to submit mutipart form from browser using XMLHTTPRequest

```javascript
var req = protocol.request({
  "hostname": host,
  "path": path,
  "method": "POST",
  "port": port,
  "headers": headers,
  "mode": "disable-fetch",
});

var form = new FormData();

form.append('file', file) 
req.write(form);
req.end();
```

So far i found out that `xhr.send(body)` call has empty `body` with 0 byte length.

**Comment by jhiesey** [comment]
Are you still having an issue with this? I could take a look.
