### ISSUE TITLE
How are you getting require('http') to resolve to this module?

### ISSUE THREAD

**Issue by ofirgeller** [jhiesey/stream-http#117]
The reason I am asking is that i'm using nwjs (a framework that lets you use the node api from the DOM) and when I try to import the node http module it resolves instead to this module which is have installed as a dependency of some other module (create-react-app).

I'm hoping if I can find out how you are doing it I can find a way to undo it to get the node http module instead.

**Comment by jhiesey** [comment]
Hi @ofirgeller, that isn't controlled by this module. It's up to whatever packages the code (in your case `nw.js` or one of its dependencies) to determine what gets replaced.

Unfortunately I'm not familiar with the internals of `nw.js` to know how it's doing the replacement, sorry.

**Comment by ofirgeller** [comment]
I know it is not done by nwjs, If it is also not done by this module,  that leaves webpack configs inside of create-react-app,  which makes a lot of sense, thanks!
