### ISSUE TITLE
Handle options.scheme instead of just protocol

### ISSUE THREAD

**Issue by ptarjan** [jhiesey/stream-http#15]
Sadly the browserify `https` module passes in `scheme`

https://github.com/substack/https-browserify/blob/master/index.js#L11

and it seems highly unmaintained judging by the rotting PRs.

Can you look at `scheme` identically to `protocol` for backwards compatibility?

I ran into this today trying to use the slack API with browserify: https://github.com/slackhq/node-slack-client/issues/71

**Comment by ptarjan** [comment]
Basically, reinstate this please: https://github.com/substack/http-browserify/commit/cf4f5a82292bb50fc94b09d335c6d6cefa4c5264

**Comment by parshap** [comment]
See also #14.

**Comment by feross** [comment]
We can just ask substack to add one of us as a maintainer. It's not that
hard to do this the right way.

**Comment by feross** [comment]
Okay, I have access to `https-browserify` on github and npm now. We can fix this directly now.

I'm traveling and busy at the moment, but if someone sends a PR to `https-browserify`, I'll merge it and publish a new version :)

**Comment by ptarjan** [comment]
@feross yay. There is one already there.

**Comment by parshap** [comment]
I think you want this one: https://github.com/substack/https-browserify/pull/2 — except maybe we can also remove the `params.scheme` line because it's not needed anymore. (Except for maybe user code that is depending on the mutation of the `params` object? :\\)

**Comment by feross** [comment]
Okay, this should be fixed now in https-browserify 0.0.1 and browserify should get the fix automatically because of semver

Can anyone confirm that this works now?

**Comment by ptarjan** [comment]
@feross I don't see an update to https-browserify when I run `ncu`. Wouldn't they have to push a new package to update their deps?

**Comment by jhiesey** [comment]
@ptarjan I agree that this should be fixed, since @feross published a new version of `https-browserify`.

If it isn't, please re-open this issue and include a test case that shows it isn't working. I'd rather not add extra compatibility code since the bug is clearly in `https-browserify` (as far as I can tell node doesn't support `opts.scheme` in the native `http` module).
