### ISSUE TITLE
Support for WebWorkers

### ISSUE THREAD

**Issue by jayfunk** [jhiesey/stream-http#22]
stream-http [assumes a normal browser window](https://github.com/jhiesey/stream-http/blob/master/lib/request.js#L101) and not a worker, though http requests in a worker are legitimate.

Inside a webworker the global object is self not window.

[Original issue in http-browserify.](https://github.com/substack/http-browserify/issues/36)

**Comment by jhiesey** [comment]
Hm, it's very easy to just replace `window` with `global`, but I wonder if there's anything else that is different between workers and the window.

I'll add a test for WebWorker support before merging that change.

**Comment by jhiesey** [comment]
Fixed by https://github.com/jhiesey/stream-http/commit/8cab16f26e1442a3f7b381432a25a736a9eb8ca5
