### ISSUE TITLE
Support for https?

### ISSUE THREAD

**Issue by goloroden** [jhiesey/stream-http#24]
First of all: Awesome work, this really is a great module and a very important improvement for browserify! Great work :-)!

What I am wondering about is whether this module already is able to support https, or - if not - whether there are any plans to do so? Is this on the roadmap in any way?

**Comment by jhiesey** [comment]
It supports https if you pass a url string that starts with 'https:' or if you pass `protocol`: `https:` in `options`.

Also, you can `require('https')`, which gives you [https-browserify](https://www.npmjs.com/package/https-browserify), which already defaults to https but uses this module underneath.
