### ISSUE TITLE
req.destroy / req.abort does not close the underlying connection

### ISSUE THREAD

**Issue by goloroden** [jhiesey/stream-http#26]
If you have an open request and call `req.destroy()`, you won't get data any longer, but the connection stays open (at least in Chrome).

So, for the server-side, there is no way to detect that the client is not interested any more in the server's data and can therefor not clean up afterwards :-(

What should I do to handle this?

**Comment by terinjokes** [comment]
In Chrome, you're likely using the WHATWG Fetch API, which currently has no way to signal an abort. See this thread: https://github.com/whatwg/fetch/issues/27

**Comment by feross** [comment]
Yeah, this is a limitation of the Fetch API. Once there's support for aborting a request, we'll add support to stream-http and your server load will magically reduced :)

**Comment by goloroden** [comment]
Thanks for your very quick replies :-)

Do you know of any timeframe that we're talking about here? Is this something that is probably going to happen in the near future, or will it take its time (weeks, months, years)?

**Comment by feross** [comment]
I would guess months. It depends on it being spec'd out and implemented by browsers, so it could turn out to be years if they don't get their act together.

I asked on Twitter: https://twitter.com/feross/status/646011172970299392

@jhiesey would be able to tell you if there's an option you can pass to force stream-http to use XHR instead of Fetch so you'll get support for abort.

**Comment by goloroden** [comment]
Thanks a lot for the detailed answer :-))

**Comment by jhiesey** [comment]
There isn't currently an option to force XHR instead of Fetch, but I agree it sounds like a good idea. Pull request welcome!

Otherwise I'll add it myself sometime soon.

**Comment by goloroden** [comment]
Being able to force this mode somehow is one thing, but how would you switch into this mode when using stream-http within browserify?

**Comment by jhiesey** [comment]
@goloroden As long as you are using `http` directly, essentially all browserify does is change `require('http')` into `require('stream-http')`. This means that you can just pass the needed options into `http.request()` or `http.get()`.

If on the other hand you are using another module that in turn requires `http`, then you won't necessarily have any way of passing the necessary options.
