### ISSUE TITLE
Uncaught TypeError: buffer.toArrayBuffer is not a function

### ISSUE THREAD

**Issue by alanshaw** [jhiesey/stream-http#35]
Thrown here: https://github.com/jhiesey/stream-http/blob/master/lib/request.js#L99

**Comment by karissa** [comment]
yep, also ran into this

**Comment by feross** [comment]
Glad we got this fixed up. :

**Comment by amertak** [comment]
I am getting this error when using watchify, when using browserify to buil, it works. You have an idea what could be the issue?

https://david-dm.org/amertak/Fractions?path=Application/www

**Comment by ideodora** [comment]
I bumped into this too thx for fix
