### ISSUE TITLE
Ability to disable use of fetch

### ISSUE THREAD

**Issue by alexjeffburke** [jhiesey/stream-http#44]
Hi there,

Would there be any traction in allowing an option to be specified that disabled the use of fetch? I'm working on a plugin for a testing framework that mocks out XHR - but simply trying to bundle it using newer versions of browserfiy without such an option results in `fetch` being automatically preferred and thus the mocking being escaped. It'd be great to be able to disable thus avoiding custom patches.

If this is something that'd be acceptable I'd be happy to look at a PR.

Thanks, Alex J Burke.

**Comment by jhiesey** [comment]
Currently there isn't, but it would definitely be nice to have.

So far I've provided some customization of the underlying implementation through setting `options.mode`. If you want to add something there, I'd take the PR.

That being said, I think I need a cleaner way of controlling which implementation is used, which I want to design sometime soon. I think it would involve an alternative to `options.mode` (which would remain for backwards compatibility only).

**Comment by alexjeffburke** [comment]
@jhiesey apologies for not getting back to you and thanks for the response! I've opened a PR that did as you suggested, added a new mode.

As for a new mechanism, I do see what you mean - in the course of the looking at this realised perhaps you'd want to request a property of one of the other modes such as explicit text or streaming. There is also an interplay with the browser in use and its capabilities so there wasn't an easy/obvious solution that sprang to mind. Will ponder it some more.
