### ISSUE TITLE
Compatibility check doesn't select 'fetch' on Chrome

### ISSUE THREAD

**Issue by gtremper** [jhiesey/stream-http#46]
First of all, thanks for this great library! It seems `ReadableByteStream` is no longer in the latest Chrome (Tried with Chrome 52.0.2743.82 (64-bit) on OS X 10.11.6). This causes the `fetch` compatibility check to fail, selecting `xhr` instead. I checked the `fetch` response body and it was a `ReadableStream`. Maybe you should check for `ReadableStream` instead, or check for either `ReadableStream` or `ReadableByteStream`. I'm not sure the best cross-platform way to do this.

Cheers

**Comment by jhiesey** [comment]
Good catch! It looks like `ReadableByteStream` has been been around as long as `ReadableStream`, so I'll just switch to that. Fix to be released in version 2.3.1.
