### ISSUE TITLE
stream-http `get` call fails on MS Edge 38

### ISSUE THREAD

**Issue by neer300** [jhiesey/stream-http#48]
Microsoft has released an anniversary [update](https://support.microsoft.com/en-us/help/12373/windows-update-faq) which updates MS Edge to version 38

On this version, stream-http `get` fails silently and no network request goes out. 

I checked the sauce-lab's test results page and looks like this version is not tested. Kindly help

**Comment by neerjoshtwitch** [comment]
I debugged some more and looks like in MS Edge version 38, the fetch ```Header``` object has a ```forEach``` function instead of an ```iterator``` . I checked out the code and ran on the local browser tests on Edge 38. The tests don't even progress past the ```#abort on response``` test

**Comment by jhiesey** [comment]
Should be fixed by #54. Confirmed working in Edge 38.
