### ISSUE TITLE
Upload failure because Chrome may fail to GC the blobs

### ISSUE THREAD

**Issue by XiaoningLiu** [jhiesey/stream-http#57]
Hi,

I'm from Microsoft and trying to make Azure Storage Node.js SDK work in the browser based on browserify. The stream-http is used to replace the http module in the project. 

**I found an interesting uploading issue related to Chrome.**
## Issue Description

I tried to upload a file more than 1GB. 
Every big file is split into 4MB trunks. 
Every trunk is uploaded by HTTP PUT based on stream-http.

However, every time the file is uploaded around 50%, the left trunks will fail. 
After one fail, we cannot upload another trunk anymore. 
Only page refresh will reset the status. 

The Chrome console will report "net::ERR_FILE_NOT_FOUND". 
![chrome_blob_errfilenotfound](https://cloud.githubusercontent.com/assets/6889160/19671522/e0b4475e-9aa1-11e6-9166-28e4e6fc388f.PNG)

Every other browsers work fine, only Chrome reports this error.
I tested on the latest Chrome Version 54.0.2840.71 m (64-bit).
## Root Cause

I did investigation for the problem. 
The root cause should on Chrome's side.

In stream-http, for Chrome, every data trunk will be send by xhr in the **blob** type.
(The logic is defined in Request.js, ClientRequest.prototype._onFinish.)

However, in my case:
1. **Chrome seems cannot auto GC the blobs used**.
2. **And Chrome also has an total blob size limitation.**

There also are related issue reports for Chrome:
1. [Blob Objects are not getting cleared once the blob object is de-referenced ](https://bugs.chromium.org/p/chromium/issues/detail?id=468718)
2. [the total blobs' size cannot exceed about 500MiB ](https://bugs.chromium.org/p/chromium/issues/detail?id=375297)

So, every time I upload a file larger than the size limit, it will totally fail.
In the screenshot, we can find that many unused 4MB blobs still with 1 reference, cannot be GC.
![chrome_blob_leak](https://cloud.githubusercontent.com/assets/6889160/19671920/d6ce702c-9aa4-11e6-8cb6-ca542f8e005f.PNG)
## Solution

Because Chrome also supports [ArrayBuffer and uInt8Array as XMLHttpRequest payloads](https://developers.google.com/web/updates/2012/07/Arrived-xhr-send-ArrayBufferView).
So I tried to pass the uInt8Array _body into uInt8Array as the payload directly.  
The modification is in the Request.js ClientRequest.prototype._onFinish.
And it works!

**Chrome seems still need long time to make changes.**
**Before Chrome makes an update for this issue.**
**We may try to use other xhr payload types instead of blob?**

Can you please help check this issue? 
I'm also willing to help solve the problem or commit some codes.

Best

**Comment by jhiesey** [comment]
I believe I used blob instead of Uint8Array or ArrayBuffer because it has better compatibility, but it sounds like I should support both. I'll look into this.

**Comment by XiaoningLiu** [comment]
Thanks for your response!
Please tell me if any help needed!

**Comment by XiaoningLiu** [comment]
Chrome seems fixed the issue in the latest nightly build version. 

https://www.google.com.tw/chrome/browser/canary.html
https://bugs.chromium.org/p/chromium/issues/detail?id=375297

**Comment by PeterRao** [comment]
Also appears on Safari of IOS 11, use ArrayBuffer can fix the issue.

**Comment by jhiesey** [comment]
OK, I'll look into this. Looks like a simple fix.
