### ISSUE TITLE
Import fails with CORS

### ISSUE THREAD

**Issue by OliveAwesomesauz** [jhiesey/stream-http#60]
My company's web stack uses CORS.  Merely importing stream-http causes a request to be made to example.com, which violates CORS and therefore causes the import to fail.  In fact, I'm not importing stream-http directly, I'm importing fetch, so I can't simply try/catch the import or anything like that.

The error appears on the line:
`Failed on xhr.open('GET', global.location.host ? '/' : 'https://example.com')`
So this is related to the previous issue.

**Comment by jhiesey** [comment]
Which browser are you seeing this in? That xhr should never actually be sent; it's created only to see what features are provided by the XMLHttpRequest object.

**Comment by OliveAwesomesauz** [comment]
I am using chrome.

**Comment by magne4000** [comment]
Same issue with last version of Chrome, no issue with last version of Firefox.

**Comment by dominictarr** [comment]
this is throwing for me, when using electron with a content-security-policy
https://github.com/ssbc/patchwork/issues/431

**Comment by ysangkok** [comment]
@jhiesey New Chrome versions will throw even on open. I don't know which version exactly changed this behavior.

**Comment by rohanprasad** [comment]
Hey, any progress with this issue ?

**Comment by jhiesey** [comment]
This should be fixed by #61

**Comment by jhiesey** [comment]
Will be included in version 2.6.0

**Comment by rohanprasad** [comment]
@jhiesey Thanks for the update. Btw when is the next version going to be released?

**Comment by jhiesey** [comment]
Should be within the next 24 hours. I'm trying to get the tests to pass, but they're being flaky due to #63
