### ISSUE TITLE
Crashes when content security policy enabled with fixed connect sources

### ISSUE THREAD

**Issue by RomanGotsiy** [jhiesey/stream-http#64]
With content security policy enabled, and the connect sources set to accept certain sources I get the following error in the console:

![image](https://cloud.githubusercontent.com/assets/3975738/21731608/c950b43a-d45d-11e6-9cdc-c56cd5aef129.png)

Seems the issues comes from this line: https://github.com/jhiesey/stream-http/blob/master/lib/capability.js#L17

How to reproduce:

serve any browser bundle (via browserify or webpack) containing `stream-http` over http-server with header `Content-Security-Policy: connect-src 'self'`.
I managed to achieve this using server from [this gist](https://gist.github.com/enjalot/2904124) and adding at line 45: `self.send_header("Content-Security-Policy", "connect-src 'self'")`.

I don't know how to fix this issue so let me know if I can help you by setting up minimal reproducible repo.

**Comment by jhiesey** [comment]
Fixed for now by #65 and published as v2.6.1
