### ISSUE TITLE
Edge's `fetch` does not allow GET with `body: null`

### ISSUE THREAD

**Issue by ldegen** [jhiesey/stream-http#68]
Hi, I am using stream-http indirectly via browserify. I think I may have hit a regression in 2.6.2

The fix for #67 triggers some misbehavior in Edge, briefly mentioned in a comment to this issue: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8546263/

The fetch API seems to disallow GET-requests with a body -- I only tried chromium and edge. Both raise an error if I try to `fetch` something with GET and an non-empty body. 
Edge seems to be particularly picky about this; here the `fetch` call reports an error, even with `body: null`.

Try this:

```javascript
// breaks in both browsers:
fetch(location.origin,{body:"barf"}).then(function(){console.log("yes");}, function(e){console.log("no", e);})
// works in chromium, but not in edge:
fetch(location.origin,{body:null}).then(function(){console.log("yes");}, function(e){console.log("no", e);})
// works in both browsers:
fetch(location.origin,{body:undefined}).then(function(){console.log("yes");}, function(e){console.log("no", e);})
```

Since 8df10e0, the `body` variable is initialized to `null`. 
For GET requests, I think it should always be `undefined`, shouldn't it. Or would that break #67 again?

**Comment by jhiesey** [comment]
Yes, you're totally right. Fix published in v2.6.3

**Comment by jhiesey** [comment]
(I fixed this last night and forgot to publish)

**Comment by ldegen** [comment]
Jeeeeesus.... that was quick :-D
