### ISSUE TITLE
CSP Issue

### ISSUE THREAD

**Issue by crisward** [jhiesey/stream-http#70]
I'm getting a Content Security Policy issue, I've traced it back through my app, from browserify to this code

https://github.com/jhiesey/stream-http/blob/master/lib/capability.js#L23

The possibility of it loading `example.com` is enough to stop my script running.

Any ideas?

**Comment by jhiesey** [comment]
This should have been fixed by https://github.com/jhiesey/stream-http/commit/43761f2799ac5f523badc315ed473e9106aa3a73

Feel free to re-open if it wasn't.
