### ISSUE TITLE
Uncaught TypeError: function Buffer(arg)

### ISSUE THREAD

**Issue by njj** [jhiesey/stream-http#79]
```
Uncaught TypeError: function Buffer(arg) {
  if (!(this instanceof Buffer)) {
    // Avoid going through an ArgumentsAdaptorTrampol...<omitted>...
} is not a function
```

Has anyone seen an error similar to this caused by this lib?  I can't seem to figure out why its happening around the time of `request.write`.

**Comment by jhiesey** [comment]
That's a weird error. What browser/environment are you using? Anything else unusual about your setup?

**Comment by njj** [comment]
@jhiesey Its a React app using browserify and I use Chrome.  It only seems to be happening on, here's the part of code I've narrowed it down to:

```
request.write(postBody);
```

**Comment by njj** [comment]
Moving to buffer lib issues.
