### ISSUE TITLE
IE11 Blob Memory Leaking

### ISSUE THREAD

**Issue by XiaoningLiu** [jhiesey/stream-http#80]
Hi,

Latest version of IE11 (11.0.43) will leaking memories when upload with Blob payload. However, IE seems only update for security reasons, not likely this can be fixed by IE:

`
We noticed you’re filing a bug against Internet Explorer 11. Note that, while Internet Explorer 11 is still supported with critical security updates, we do not plan further feature updates. All new feature work is focused on Microsoft Edge at this time. For this reason, only high-impact security bugs will be considered for Internet Explorer servicing.
`

For IE11, stream-http will create Blob objects as the fetch/xhr payloads. The memory leaking happens especially uploading is parallel. Whether per uploading request is successful, the leak will always happen. Closing or refresh the IE tab will not help GC the leaked memory.

Here is a leaking demo:
https://ie11-memory-leak.azurewebsites.net/api/HttpTriggerJS1

Can stream-http provide an option for the preferred payload type, or disabling the Blob type payload?

**Comment by jhiesey** [comment]
I'll take a look soon

**Comment by jhiesey** [comment]
Fixed in https://github.com/jhiesey/stream-http/commit/16c1baf1781bd345083adc84bdad5012b6450e57
