### ISSUE TITLE
In fetch mode the setTimeout was not cleared ;Maybe I can not understand what you mean clearly

### ISSUE THREAD

**Issue by luozhang002** [jhiesey/stream-http#85]
description:
in stream-http/request.js file .There is some code .please look at the picture:
<img width="552" alt="2018-05-03 12 51 12" src="https://user-images.githubusercontent.com/5653578/39560434-b5a5ac08-4ed0-11e8-8c55-5aaa8f99627e.png">

chrome edition:

![2018-05-03 1 53 52](https://user-images.githubusercontent.com/5653578/39561648-8c2921c6-4ed9-11e8-9181-f08d0340a795.png)

safari edition:
<img width="317" alt="2018-05-03 1 58 03" src="https://user-images.githubusercontent.com/5653578/39561774-696caca6-4eda-11e8-93eb-c7ee57cf8aaa.png">

in fetch mode you define global.setTimeout (condition:capability.abortController ) to emit requestTimeout event ,but i can not see the function clearTimeout in this code.i do not know clearly.  because in our sdk we monitor an event requestTimeout, it continually  throws warn  But when I add clearTiimeout in the library ,it works well. so  i think it is a emergency issue for us.Thank you very much.

**Comment by jhiesey** [comment]
Should be fixed by https://github.com/jhiesey/stream-http/commit/472ed03ea7e463b8270a6f3728ed85d775b1cace

**Comment by jhiesey** [comment]
Automated tests are failing, I think because of https://status.saucelabs.com/incidents/tm272kz6yb5t

Running tests manually

**Comment by jhiesey** [comment]
Fix released in v2.8.2
